services:
  - type: background_worker
    name: dona-slack-bot
    runtime: python3
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.app
    repo: https://github.com/AutonomosCdM/autonomos_dona
    branch: main
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN  
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_WORKSPACE_ID
        sync: false
      - key: SUPABASE_URL
        value: https://wqqxctsyoeoqcqkoaagv.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcXhjdHN5b2VvcWNxa29hYWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzQ5OTgsImV4cCI6MjA2NDY1MDk5OH0.G36sYmBucD8Ow058j2lrTsLQIQRQGfuRi6_cb6Cmjs8
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "False"
      - key: ENV
        value: production
      - key: RATE_LIMIT_ENABLED
        value: "True"
      - key: RATE_LIMIT_USER_MAX
        value: "60"
      - key: RATE_LIMIT_USER_BURST
        value: "10"
      - key: RATE_LIMIT_CLEANUP_INTERVAL
        value: "3600"
      - key: PYTHON_VERSION
        value: "3.9"