name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
          perf
          ci
          revert
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.

  size-label:
    name: Add Size Label
    runs-on: ubuntu-latest
    
    steps:
    - name: Add size label
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/XS'
        xs_max_size: '10'
        s_label: 'size/S'
        s_max_size: '100'
        m_label: 'size/M'
        m_max_size: '500'
        l_label: 'size/L'
        l_max_size: '1000'
        xl_label: 'size/XL'
        fail_if_xl: 'false'

  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto assign PR
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: '.github/auto-assign.yml'

  conflicts:
    name: Check Conflicts
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for merge conflicts
      uses: eps1lon/actions-label-merge-conflict@v3
      with:
        dirtyLabel: "conflicts"
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
        commentOnClean: "Conflicts have been resolved. The pull request is ready for review."